/*
 * EcoSort — Waste Knowledge Base (v2, 28 items)
 * --------------------------------
 * Curated dataset powering DEMO MODE. Same shape as Live AI output
 * (see server.js), so UI is identical in both modes.
 * Bin colours follow India's SWM Rules 2016:
 * Green = wet, Blue = dry, Red/Hazard = special, Purple = conditional.
 */

const WASTE_DB = {
  plastic_bottle: {
    name: "Plastic Bottle (PET)",
    emoji: "🧴",
    category: "Recyclable Plastic",
    recyclable: "yes",
    bin: "Blue / Dry Waste",
    binColor: "#1d4ed8",
    confidence: 0.97,
    prep: ["Empty all liquid", "Rinse lightly", "Crush to save space", "Leave the cap on — modern recyclers handle it"],
    decompose: "450 years if landfilled",
    co2: "Recycling 1 kg of PET avoids ~1.5 kg CO₂ vs. new plastic.",
    tip: "PET (resin code #1) is one of the most valuable recyclables. Keep it dry and clean.",
  },
  glass_bottle: {
    name: "Glass Bottle / Jar",
    emoji: "🍾",
    category: "Recyclable Glass",
    recyclable: "yes",
    bin: "Blue / Dry Waste",
    binColor: "#1d4ed8",
    confidence: 0.95,
    prep: ["Rinse out residue", "Remove metal/plastic lids (recycle separately)", "Do NOT break the glass"],
    decompose: "1 million+ years (effectively never)",
    co2: "Glass is infinitely recyclable; recycled glass cuts furnace energy ~30%.",
    tip: "Broken glass injures waste pickers — keep bottles whole, bag shards separately and label.",
  },
  food_waste: {
    name: "Food / Kitchen Waste",
    emoji: "🍎",
    category: "Organic / Compostable",
    recyclable: "compost",
    bin: "Green / Wet Waste",
    binColor: "#15803d",
    confidence: 0.93,
    prep: ["Keep free of plastic and cutlery", "Drain excess liquid", "Compost at home if possible"],
    decompose: "2–6 weeks when composted",
    co2: "Composting food waste instead of landfilling avoids methane — 1 tonne diverted ≈ 0.5 t CO₂e.",
    tip: "Food in landfill releases methane, ~28× more warming than CO₂. Composting is the biggest household win.",
  },
  paper: {
    name: "Paper / Newspaper",
    emoji: "📄",
    category: "Recyclable Paper",
    recyclable: "yes",
    bin: "Blue / Dry Waste",
    binColor: "#1d4ed8",
    confidence: 0.92,
    prep: ["Keep dry", "Remove plastic windows/tape", "Flatten to save space"],
    decompose: "2–6 weeks",
    co2: "1 tonne of recycled paper saves ~17 trees and ~26,000 L of water.",
    tip: "Wet or greasy paper cannot be recycled — fibres clog the pulping process.",
  },
  cardboard: {
    name: "Cardboard / Carton",
    emoji: "📦",
    category: "Recyclable Paper",
    recyclable: "yes",
    bin: "Blue / Dry Waste",
    binColor: "#1d4ed8",
    confidence: 0.94,
    prep: ["Flatten the box", "Remove tape and plastic labels", "Keep dry"],
    decompose: "2 months",
    co2: "Recycling cardboard uses ~75% less energy than making it new.",
    tip: "Flatten boxes — un-flattened boxes waste truck space and raise collection emissions.",
  },
  battery: {
    name: "Battery",
    emoji: "🔋",
    category: "Hazardous / E-waste",
    recyclable: "special",
    bin: "E-waste / Hazardous Drop-off",
    binColor: "#b91c1c",
    confidence: 0.96,
    prep: ["NEVER put in regular bins", "Tape terminals of lithium cells", "Take to an e-waste collection point"],
    decompose: "Leaches toxic metals indefinitely",
    co2: "Recovers lithium, cobalt and nickel — reduces destructive new mining.",
    tip: "A single button cell can contaminate ~600,000 L of water. Never general waste.",
  },
  ewaste: {
    name: "Electronics / E-waste",
    emoji: "📱",
    category: "Hazardous / E-waste",
    recyclable: "special",
    bin: "E-waste Drop-off",
    binColor: "#b91c1c",
    confidence: 0.9,
    prep: ["Wipe personal data", "Remove batteries if possible", "Use certified e-waste recycler / take-back program"],
    decompose: "Never; leaches lead and mercury",
    co2: "Recovers gold, copper and rare earths — 1 t of phones holds more gold than 1 t of ore.",
    tip: "India generates ~1.7M tonnes of e-waste/year. Use certified recyclers only.",
  },
  tetrapak: {
    name: "Tetra Pak / Juice Carton",
    emoji: "🧃",
    category: "Multi-layer Carton",
    recyclable: "conditional",
    bin: "Blue / Dry Waste (where accepted)",
    binColor: "#7c3aed",
    confidence: 0.82,
    prep: ["Empty and rinse", "Flatten", "Push straw inside or remove cap", "Check if your area accepts cartons"],
    decompose: "~30 years",
    co2: "Paper + plastic + aluminium layers need specialised de-laminating plants.",
    tip: "Not every city accepts cartons. Check locally before binning.",
  },
  plastic_bag: {
    name: "Plastic Bag / Film",
    emoji: "🛍️",
    category: "Soft Plastic",
    recyclable: "conditional",
    bin: "Dry Waste — store drop-off, NOT curbside",
    binColor: "#7c3aed",
    confidence: 0.85,
    prep: ["Keep clean and dry", "Bundle bags together", "Return to supermarket soft-plastic bin"],
    decompose: "20–500 years",
    co2: "Soft plastics jam curbside machinery — they need a separate stream.",
    tip: "Soft plastic is the top contaminant in recycling bins. Reuse first, drop-off only.",
  },
  aluminium_can: {
    name: "Aluminium Can",
    emoji: "🥫",
    category: "Recyclable Metal",
    recyclable: "yes",
    bin: "Blue / Dry Waste",
    binColor: "#1d4ed8",
    confidence: 0.96,
    prep: ["Empty and rinse", "Lightly crush", "No need to remove the label"],
    decompose: "200+ years if landfilled",
    co2: "Recycling aluminium uses 95% less energy than new — best ROI of any material.",
    tip: "A can recycled today can be back on a shelf in ~60 days. Infinitely recyclable.",
  },
  styrofoam: {
    name: "Styrofoam / Thermocol",
    emoji: "🍱",
    category: "Non-recyclable Plastic",
    recyclable: "no",
    bin: "Black / General Waste",
    binColor: "#374151",
    confidence: 0.88,
    prep: ["Most curbside programs reject it", "Avoid buying where possible", "Reuse for packaging/crafts"],
    decompose: "500+ years; breaks into microplastics",
    co2: "Expanded polystyrene is 95% air — uneconomic to recycle in most places.",
    tip: "Refuse first: choose paper or compostable packaging instead.",
  },
  pizza_box: {
    name: "Pizza Box (greasy)",
    emoji: "🍕",
    category: "Mixed (paper + food)",
    recyclable: "conditional",
    bin: "Tear it: clean lid → Blue, greasy base → Green/compost",
    binColor: "#7c3aed",
    confidence: 0.8,
    prep: ["Tear off clean cardboard → recycle", "Greasy/cheesy parts → compost or general", "Remove any plastic"],
    decompose: "Clean card: 2 months",
    co2: "Grease ruins a whole paper-recycling batch — separation keeps clean fibre valuable.",
    tip: "Classic trap: NOT all-recyclable. Split clean from soiled.",
  },
  textile: {
    name: "Clothes / Textile",
    emoji: "👕",
    category: "Textile",
    recyclable: "reuse",
    bin: "Donation / Textile recycling bin",
    binColor: "#0891b2",
    confidence: 0.87,
    prep: ["Wearable → donate", "Worn out → textile recycling bank", "Never to general waste"],
    decompose: "Natural: months · Synthetic: 20–200 years",
    co2: "One cotton T-shirt takes ~2,700 L of water — extending life beats recycling.",
    tip: "Reuse and donate before recycling. Fast fashion is a top polluter.",
  },
  medicine: {
    name: "Expired Medicines",
    emoji: "💊",
    category: "Hazardous / Medical",
    recyclable: "special",
    bin: "Pharmacy take-back / Hazardous",
    binColor: "#b91c1c",
    confidence: 0.93,
    prep: ["Never bin or flush", "Keep in original strip/pack", "Hand to pharmacy take-back or hazardous drop-off"],
    decompose: "Contaminates water and soil indefinitely",
    co2: "Safe collection prevents pharmaceutical pollution of rivers and groundwater.",
    tip: "Ask your pharmacist — most cities have a take-back box even if unadvertised.",
  },
  sanitary_waste: {
    name: "Sanitary / Diapers",
    emoji: "🩹",
    category: "Sanitary Waste",
    recyclable: "no",
    bin: "Red / Sanitary (wrapped, labelled)",
    binColor: "#b91c1c",
    confidence: 0.9,
    prep: ["Wrap securely in newspaper", "Mark with red dot / label sanitary", "Keep separate from recyclables"],
    decompose: "250–500 years; hygiene risk if mixed",
    co2: "Segregation protects waste pickers from infection and keeps recyclables clean.",
    tip: "SWM 2016: wrap sanitary waste separately. Never mix with dry recyclables.",
  },
  cfl_bulb: {
    name: "CFL / Tube-light / Bulb",
    emoji: "💡",
    category: "Hazardous (mercury)",
    recyclable: "special",
    bin: "E-waste / Hazardous Drop-off",
    binColor: "#b91c1c",
    confidence: 0.91,
    prep: ["Do NOT break", "Wrap in original box/newspaper", "Take to e-waste or hazardous point"],
    decompose: "Never; mercury leaches if broken",
    co2: "One CFL holds ~4mg mercury — enough to pollute thousands of litres if broken in landfill.",
    tip: "LEDs are safer and last longer — switch when replacing.",
  },
  paint_can: {
    name: "Paint / Chemical Can",
    emoji: "🎨",
    category: "Hazardous",
    recyclable: "special",
    bin: "Hazardous Drop-off (dried cans → scrap)",
    binColor: "#b91c1c",
    confidence: 0.86,
    prep: ["Never pour down drain", "Dry out leftover with sand/newspaper", "Take to hazardous collection"],
    decompose: "Leaches solvents and heavy metals",
    co2: "Solvents contaminate soil and water treatment — collection keeps them out of drains.",
    tip: "Buy only what you need. Share leftover paint before dumping.",
  },
  cooking_oil: {
    name: "Used Cooking Oil",
    emoji: "🫗",
    category: "Organic / Hazardous if dumped",
    recyclable: "special",
    bin: "Collection bottle → aggregator (RUCO)",
    binColor: "#b91c1c",
    confidence: 0.88,
    prep: ["Cool, strain, store in bottle", "Never pour in sink", "Give to RUCO/biodiesel collector"],
    decompose: "Clogs drains and waterways within days",
    co2: "1 L oil can pollute ~1M L water. Collected oil becomes biodiesel.",
    tip: "India RUCO program buys used oil for biodiesel — your society can enroll.",
  },
  coffee_cup: {
    name: "Disposable Coffee Cup",
    emoji: "☕",
    category: "Mixed (paper + plastic lining)",
    recyclable: "conditional",
    bin: "General / check local cup recycling",
    binColor: "#7c3aed",
    confidence: 0.83,
    prep: ["Empty and rinse", "Remove lid and sleeve (recycle separately)", "Carry reusable next time"],
    decompose: "20–30 years; lining blocks pulping",
    co2: "Plastic lining makes most cups unrecyclable curbside despite the paper look.",
    tip: "Reusable cup is the fix — many cafes give a discount for it.",
  },
  milk_pouch: {
    name: "Milk Pouch / Sachet",
    emoji: "🥛",
    category: "Soft Plastic (MLP)",
    recyclable: "conditional",
    bin: "Blue / Dry (rinsed) or MLP collection",
    binColor: "#7c3aed",
    confidence: 0.84,
    prep: ["Rinse", "Dry and bundle", "Hand to dry-waste / MLP collector"],
    decompose: "50–100 years",
    co2: "Clean, bundled pouches get recycled; dirty ones contaminate the whole bag.",
    tip: "Maharashtra and others have buy-back / EPR collection for milk pouches.",
  },
  garden_waste: {
    name: "Garden / Leaf Waste",
    emoji: "🍂",
    category: "Organic / Compostable",
    recyclable: "compost",
    bin: "Green / Wet Waste or compost pit",
    binColor: "#15803d",
    confidence: 0.94,
    prep: ["No plastic pots or ties", "Chop bulky branches", "Compost or community pit"],
    decompose: "1–3 months composted",
    co2: "Burning leaves creates PM2.5 smog — composting avoids it entirely.",
    tip: "Never burn garden waste. Leaf compost is free fertiliser in ~8 weeks.",
  },
  metal_scrap: {
    name: "Metal Scrap / Utensils",
    emoji: "🔩",
    category: "Recyclable Metal",
    recyclable: "yes",
    bin: "Blue / Dry or kabadiwala",
    binColor: "#1d4ed8",
    confidence: 0.93,
    prep: ["Remove food residue", "Separate sharp items safely", "Sell/give to scrap dealer"],
    decompose: "50–500 years; rusts but never disappears",
    co2: "Steel recycling saves ~60% energy; kabadiwala networks already recycle ~30% in India.",
    tip: "Kabadiwala is circular economy OG — segregate metal, it never goes waste.",
  },
  old_shoes: {
    name: "Old Shoes / Footwear",
    emoji: "👟",
    category: "Mixed / Textile + Rubber",
    recyclable: "reuse",
    bin: "Donation / Textile bin if wearable",
    binColor: "#0891b2",
    confidence: 0.82,
    prep: ["Clean pair → donate", "Single/worn → textile recycling", "Tie pairs together"],
    decompose: "25–50 years (rubber soles persist)",
    co2: "Extending shoe life by 9 months cuts its footprint ~30%.",
    tip: "Many brands now take back old pairs for sole-grinding programs.",
  },
  ceramic_waste: {
    name: "Broken Ceramic / Crockery",
    emoji: "🍶",
    category: "Non-recyclable Inert",
    recyclable: "no",
    bin: "Black / General (wrapped, labelled)",
    binColor: "#374151",
    confidence: 0.89,
    prep: ["Wrap shards thickly", "Label SHARP", "Keep out of glass recycling"],
    decompose: "Effectively forever; inert but not recyclable",
    co2: "Ceramic melts at far higher temp than glass — one shard ruins a glass batch.",
    tip: "Never put ceramic in glass bins. Wrap and label for picker safety.",
  },
  temple_flowers: {
    name: "Temple / Puja Flowers",
    emoji: "🌸",
    category: "Organic / Compostable",
    recyclable: "compost",
    bin: "Green / Wet or flower-cycling bin",
    binColor: "#15803d",
    confidence: 0.95,
    prep: ["Remove plastic threads and polythene", "Compost or flower-cycling NGO", "Never river-dump in plastic bags"],
    decompose: "2–4 weeks composted",
    co2: "River-dumped flowers in plastic choke ghats; composted they become incense and dye.",
    tip: "8M tonnes of temple flowers yearly in India — composting or incense startups close the loop.",
  },
  coconut_shell: {
    name: "Coconut Shell / Husk",
    emoji: "🥥",
    category: "Organic / Compostable",
    recyclable: "compost",
    bin: "Green / Wet or coir collection",
    binColor: "#15803d",
    confidence: 0.92,
    prep: ["No plastic", "Give husk to coir collector if available", "Shells compost slowly — chop"],
    decompose: "2–12 months; coir is slow",
    co2: "Coir becomes mats, pots and fuel — burning husk wastes value and smokes.",
    tip: "Coconut vendors often take husks back — ask before binning.",
  },
  disposable_cutlery: {
    name: "Plastic Cutlery / Straws",
    emoji: "🍴",
    category: "Single-use Plastic",
    recyclable: "no",
    bin: "Black / General (avoid first)",
    binColor: "#374151",
    confidence: 0.87,
    prep: ["Refuse first", "Carry steel set", "If used, bin — too small to recycle"],
    decompose: "100–500 years; top beach litter",
    co2: "Too small and food-soiled for sorters — most fall through and jam machines.",
    tip: "Banned single-use items in India since 2022 — carry reusables.",
  },
  ink_cartridge: {
    name: "Ink / Toner Cartridge",
    emoji: "🖨️",
    category: "E-waste / Hazardous",
    recyclable: "special",
    bin: "E-waste / Manufacturer take-back",
    binColor: "#b91c1c",
    confidence: 0.85,
    prep: ["Bag to avoid leaks", "Return to OEM refill/take-back", "Never general waste"],
    decompose: "450+ years; inks leach",
    co2: "Refilled cartridges save ~80% of new-manufacture footprint.",
    tip: "Refill beats recycle — one refill saves ~2.5kg CO₂ vs new.",
  },
};

const KEYWORD_INDEX = [
  { keys: ["plastic bottle", "pet", "water bottle", "soda bottle", "coke", "bisleri"], id: "plastic_bottle" },
  { keys: ["glass", "jar", "wine", "beer bottle"], id: "glass_bottle" },
  { keys: ["food", "banana", "apple", "vegetable", "fruit", "leftover", "peel", "organic", "kitchen", "rice", "roti", "dal"], id: "food_waste" },
  { keys: ["paper", "newspaper", "magazine", "notebook", "envelope", "book"], id: "paper" },
  { keys: ["cardboard", "carton box", "corrugated", "box", "amazon box", "flipkart"], id: "cardboard" },
  { keys: ["battery", "cell", "aa ", "aaa", "lithium", "duracell"], id: "battery" },
  { keys: ["phone", "laptop", "charger", "cable", "electronic", "e-waste", "ewaste", "wire", "circuit", "tablet"], id: "ewaste" },
  { keys: ["tetra", "juice", "milk carton", "tetrapak", "amul kool", "real juice"], id: "tetrapak" },
  { keys: ["plastic bag", "polythene", "wrapper", "film", "polybag", "carry bag", "chips packet", " lays"], id: "plastic_bag" },
  { keys: ["can", "aluminium", "aluminum", "tin", "soda can"], id: "aluminium_can" },
  { keys: ["styrofoam", "thermocol", "polystyrene", "foam"], id: "styrofoam" },
  { keys: ["pizza"], id: "pizza_box" },
  { keys: ["cloth", "shirt", "textile", "fabric", "jeans", "garment", "tshirt", "kurta", "saree"], id: "textile" },
  { keys: ["medicine", "tablet", "syrup", "pill", "drug", "expired", "paracetamol", "capsule"], id: "medicine" },
  { keys: ["sanitary", "pad", "diaper", "napkin"], id: "sanitary_waste" },
  { keys: ["bulb", "cfl", "tube", "tubelight", "led bulb"], id: "cfl_bulb" },
  { keys: ["paint", "chemical", "varnish", "solvent", "thinner"], id: "paint_can" },
  { keys: ["oil", "cooking oil", "used oil", "ghee", "mustard oil"], id: "cooking_oil" },
  { keys: ["coffee", "cup", "paper cup", "chai cup", "starbucks"], id: "coffee_cup" },
  { keys: ["milk pouch", "milk packet", "milk cover", "amul", "dairy"], id: "milk_pouch" },
  { keys: ["leaf", "leaves", "garden", "grass", "twig", "branch", "plant"], id: "garden_waste" },
  { keys: ["metal", "steel", "utensil", "scrap", "iron", "vessel", "bartan"], id: "metal_scrap" },
  { keys: ["shoe", "chappal", "sandal", "footwear", "slipper", "sneaker"], id: "old_shoes" },
  { keys: ["ceramic", "crockery", "plate", "cup broken", "tile", "clay pot"], id: "ceramic_waste" },
  { keys: ["flower", "puja", "temple", "mala", "marigold", "prasad"], id: "temple_flowers" },
  { keys: ["coconut", "nariyal", "husk", "coir"], id: "coconut_shell" },
  { keys: ["cutlery", "spoon", "fork", "straw", "disposable", "plastic spoon"], id: "disposable_cutlery" },
  { keys: ["ink", "toner", "cartridge", "printer"], id: "ink_cartridge" },
];

const BIN_GUIDE = [
  { color: "#15803d", name: "Green — Wet", items: "Food, leaves, flowers, coconut, garden waste", tip: "No plastic. Compost it." },
  { color: "#1d4ed8", name: "Blue — Dry", items: "Bottles, paper, cans, metal, rinsed pouches", tip: "Clean and dry only." },
  { color: "#b91c1c", name: "Red — Hazardous / E-waste", items: "Batteries, bulbs, paint, oil, medicines, e-waste", tip: "Never mix. Drop-off only." },
  { color: "#374151", name: "Black — General", items: "Styrofoam, ceramic, cutlery, sanitary (wrapped)", tip: "Last resort. Refuse first." },
];

const QUIZ = [
  { q: "Greasy pizza box — where does it go?", options: ["Full box in Blue bin", "Tear: clean lid Blue, greasy base Green", "Full box in Green bin", "Burn it"], answer: 1, why: "Grease ruins paper recycling. Split clean from soiled." },
  { q: "Old AA batteries?", options: ["Green bin", "Blue bin", "E-waste drop-off, terminals taped", "Flush"], answer: 2, why: "One button cell can pollute 600,000 L water." },
  { q: "Milk pouch after use?", options: ["Dusty bin as-is", "Rinse, dry, bundle for dry waste", "Toilet", "Burn"], answer: 1, why: "Clean bundled pouches recycle; dirty ones contaminate." },
  { q: "Temple flowers?", options: ["River in plastic bag", "Green / compost, no plastic", "Blue bin", "Black bin"], answer: 1, why: "Flowers compost in weeks; plastic bags choke ghats." },
  { q: "Broken CFL bulb?", options: ["Blue bin with glass", "Wrap, e-waste drop-off, do not break", "Green bin", "General bin loose"], answer: 1, why: "CFL has mercury vapour. Never mix with glass." },
];

if (typeof module !== "undefined") module.exports = { WASTE_DB, KEYWORD_INDEX, BIN_GUIDE, QUIZ };
