/*
 * EcoSort — Waste Knowledge Base
 * --------------------------------
 * This is the curated dataset that powers DEMO MODE (no API key / no cost).
 * In REAL-AI MODE the same fields are produced by a Claude vision model
 * (see server.js + the system prompt in README.md), so the UI is identical
 * whether the answer comes from this table or from the live model.
 *
 * Bin colour convention follows India's Solid Waste Management Rules 2016
 * (Green = wet/biodegradable, Blue = dry/recyclable, Black/Red = hazardous,
 *  plus dedicated E-waste streams). These map cleanly to most municipal
 *  two/three-bin systems worldwide.
 */

const WASTE_DB = {
  plastic_bottle: {
    name: "Plastic Bottle (PET)",
    emoji: "🧴",
    category: "Recyclable Plastic",
    recyclable: "yes",
    bin: "Blue / Dry Waste",
    binColor: "#1d4ed8",
    confidence: 0.97,
    prep: ["Empty all liquid", "Rinse lightly", "Crush to save space", "Leave the cap on — modern recyclers handle it"],
    decompose: "450 years if landfilled",
    co2: "Recycling 1 kg of PET avoids ~1.5 kg CO₂ vs. new plastic.",
    tip: "PET (resin code #1) is one of the most valuable recyclables. Keep it dry and clean to keep it in the loop.",
  },
  glass_bottle: {
    name: "Glass Bottle / Jar",
    emoji: "🍾",
    category: "Recyclable Glass",
    recyclable: "yes",
    bin: "Blue / Dry Waste",
    binColor: "#1d4ed8",
    confidence: 0.95,
    prep: ["Rinse out residue", "Remove metal/plastic lids (recycle separately)", "Do NOT break the glass"],
    decompose: "1 million+ years (effectively never)",
    co2: "Glass is infinitely recyclable; recycled glass cuts furnace energy ~30%.",
    tip: "Broken glass is a hazard for waste pickers — keep bottles whole and bag any shards separately.",
  },
  food_waste: {
    name: "Food / Kitchen Waste",
    emoji: "🍎",
    category: "Organic / Compostable",
    recyclable: "compost",
    bin: "Green / Wet Waste",
    binColor: "#15803d",
    confidence: 0.93,
    prep: ["Keep free of plastic and cutlery", "Drain excess liquid", "Compost at home if possible"],
    decompose: "2–6 weeks when composted",
    co2: "Composting food waste instead of landfilling avoids methane — 1 tonne diverted ≈ 0.5 t CO₂e.",
    tip: "Food scraps in a sealed landfill release methane, ~28× more warming than CO₂. Composting is the single biggest household win.",
  },
  paper: {
    name: "Paper / Newspaper",
    emoji: "📄",
    category: "Recyclable Paper",
    recyclable: "yes",
    bin: "Blue / Dry Waste",
    binColor: "#1d4ed8",
    confidence: 0.92,
    prep: ["Keep dry", "Remove plastic windows/tape", "Flatten to save space"],
    decompose: "2–6 weeks",
    co2: "1 tonne of recycled paper saves ~17 trees and ~26,000 L of water.",
    tip: "Wet or greasy paper can't be recycled — the fibres clog the pulping process.",
  },
  cardboard: {
    name: "Cardboard / Carton",
    emoji: "📦",
    category: "Recyclable Paper",
    recyclable: "yes",
    bin: "Blue / Dry Waste",
    binColor: "#1d4ed8",
    confidence: 0.94,
    prep: ["Flatten the box", "Remove tape and plastic labels", "Keep dry"],
    decompose: "2 months",
    co2: "Recycling cardboard uses ~75% less energy than making it new.",
    tip: "Flattening matters: un-flattened boxes waste truck space and increase collection emissions.",
  },
  battery: {
    name: "Battery",
    emoji: "🔋",
    category: "Hazardous / E-waste",
    recyclable: "special",
    bin: "E-waste / Hazardous Drop-off",
    binColor: "#b91c1c",
    confidence: 0.96,
    prep: ["NEVER put in regular bins", "Tape the terminals of lithium cells", "Take to an e-waste collection point"],
    decompose: "Leaches toxic metals indefinitely",
    co2: "Recovers lithium, cobalt & nickel — reduces destructive new mining.",
    tip: "A single button cell can contaminate ~600,000 L of water. Batteries are never general waste.",
  },
  ewaste: {
    name: "Electronics / E-waste",
    emoji: "📱",
    category: "Hazardous / E-waste",
    recyclable: "special",
    bin: "E-waste Drop-off",
    binColor: "#b91c1c",
    confidence: 0.9,
    prep: ["Wipe personal data", "Remove batteries if possible", "Use a certified e-waste recycler / take-back program"],
    decompose: "Never; leaches lead & mercury",
    co2: "Recovers gold, copper & rare earths — 1 t of phones holds more gold than 1 t of ore.",
    tip: "India generates ~1.7 M tonnes of e-waste/year. Certified recyclers recover value AND prevent toxic leaching.",
  },
  tetrapak: {
    name: "Tetra Pak / Juice Carton",
    emoji: "🧃",
    category: "Multi-layer Carton",
    recyclable: "conditional",
    bin: "Blue / Dry Waste (where accepted)",
    binColor: "#7c3aed",
    confidence: 0.82,
    prep: ["Empty and rinse", "Flatten", "Push the straw inside or remove plastic cap", "Check if your area accepts cartons"],
    decompose: "~30 years",
    co2: "Made of paper + plastic + aluminium layers; specialised recyclers can separate them.",
    tip: "Not every municipality accepts cartons — they need a special de-laminating plant. Check locally.",
  },
  plastic_bag: {
    name: "Plastic Bag / Film",
    emoji: "🛍️",
    category: "Soft Plastic",
    recyclable: "conditional",
    bin: "Dry Waste — store drop-off, NOT curbside",
    binColor: "#7c3aed",
    confidence: 0.85,
    prep: ["Keep clean and dry", "Bundle bags together", "Return to a supermarket soft-plastic bin"],
    decompose: "20–500 years",
    co2: "Soft plastics jam curbside sorting machinery — they need a separate stream.",
    tip: "Soft plastic is the #1 contaminant in recycling bins. Reuse first; drop-off only at collection points.",
  },
  aluminium_can: {
    name: "Aluminium Can",
    emoji: "🥫",
    category: "Recyclable Metal",
    recyclable: "yes",
    bin: "Blue / Dry Waste",
    binColor: "#1d4ed8",
    confidence: 0.96,
    prep: ["Empty and rinse", "Lightly crush", "No need to remove the label"],
    decompose: "200+ years if landfilled",
    co2: "Recycling aluminium uses 95% less energy than new — the best ROI of any material.",
    tip: "An aluminium can recycled today can be back on a shelf in ~60 days. Recycle endlessly.",
  },
  styrofoam: {
    name: "Styrofoam / Thermocol",
    emoji: "🍱",
    category: "Non-recyclable Plastic",
    recyclable: "no",
    bin: "Black / General Waste",
    binColor: "#374151",
    confidence: 0.88,
    prep: ["Most curbside programs reject it", "Avoid buying where possible", "Reuse for packaging/crafts"],
    decompose: "500+ years; breaks into microplastics",
    co2: "Expanded polystyrene is 95% air — uneconomic to recycle in most places.",
    tip: "The most sustainable move is refusal: choose paper or compostable packaging instead.",
  },
  pizza_box: {
    name: "Pizza Box (greasy)",
    emoji: "🍕",
    category: "Mixed (paper + food)",
    recyclable: "conditional",
    bin: "Tear it: clean lid → Blue, greasy base → Green/compost",
    binColor: "#7c3aed",
    confidence: 0.8,
    prep: ["Tear off clean cardboard → recycle", "Greasy/cheesy parts → compost or general", "Remove any plastic"],
    decompose: "Clean card: 2 months",
    co2: "Grease ruins a whole paper-recycling batch — separation keeps the clean fibre valuable.",
    tip: "Classic trick question! A greasy pizza box is NOT all-recyclable. Split clean from soiled.",
  },
  textile: {
    name: "Clothes / Textile",
    emoji: "👕",
    category: "Textile",
    recyclable: "reuse",
    bin: "Donation / Textile recycling bin",
    binColor: "#0891b2",
    confidence: 0.87,
    prep: ["Wearable → donate", "Worn out → textile recycling bank", "Never to general waste"],
    decompose: "Natural: months · Synthetic: 20–200 years",
    co2: "One cotton T-shirt takes ~2,700 L of water to make — extending its life beats recycling.",
    tip: "Fast fashion is a top-5 polluting industry. Reuse and donate before recycling.",
  },
};

// Keyword index so the demo classifier and chat can match free text / filenames.
const KEYWORD_INDEX = [
  { keys: ["plastic bottle", "pet", "water bottle", "soda bottle", "coke"], id: "plastic_bottle" },
  { keys: ["glass", "jar", "wine", "beer bottle"], id: "glass_bottle" },
  { keys: ["food", "banana", "apple", "vegetable", "fruit", "leftover", "peel", "organic", "kitchen"], id: "food_waste" },
  { keys: ["paper", "newspaper", "magazine", "notebook", "envelope"], id: "paper" },
  { keys: ["cardboard", "carton box", "corrugated", "box"], id: "cardboard" },
  { keys: ["battery", "cell", "aa ", "aaa", "lithium"], id: "battery" },
  { keys: ["phone", "laptop", "charger", "cable", "electronic", "e-waste", "ewaste", "wire", "circuit"], id: "ewaste" },
  { keys: ["tetra", "juice", "milk carton", "tetrapak"], id: "tetrapak" },
  { keys: ["plastic bag", "polythene", "wrapper", "film", "polybag"], id: "plastic_bag" },
  { keys: ["can", "aluminium", "aluminum", "tin", "soda can"], id: "aluminium_can" },
  { keys: ["styrofoam", "thermocol", "polystyrene", "foam"], id: "styrofoam" },
  { keys: ["pizza"], id: "pizza_box" },
  { keys: ["cloth", "shirt", "textile", "fabric", "jeans", "garment"], id: "textile" },
];

if (typeof module !== "undefined") module.exports = { WASTE_DB, KEYWORD_INDEX };
